### PR TITLE
Fix function parse range

### LINKED ISSUE #179: Fix function parse range:
Some functions are out of range.
e.g.) [`assert_true()`](https://deno.land/x/denops_std@v4.1.1/function/vim/mod.ts?s=assert_true)

### PR DESCRIPTION
**Pull request by Milly**
Closes #179

### CODE REVIEW

File: scripts/gen-function/parse.ts [hunk 1]
```diff
@@ -15,13 +15,16 @@ import { Counter, regexIndexOf } from "./utils.ts";
...
   const definitions: Definition[] = [];
   for (const match of content.matchAll(/\*(\w+?)\(\)\*/g)) {
     const fn = match[1];
-    const i = match.index || 0;
+    const i = match.index ?? 0;
     const s = content.lastIndexOf("\n", i);
-    const ms = regexIndexOf(content, /\n[<>\s]/, i);
-    const me = regexIndexOf(content, /\n[^<>\s]/, ms);
+    const ms = regexIndexOf(content, /\n[<>\s]|$/, i);
+    const me = regexIndexOf(content, /\n[^<>\s]|$/, ms);
```
Comment (Milly) [inline scripts/gen-function/parse.ts:27]: `ms` or `me` may resolve to `-1`.
Then the range will be resolved from the beginning of the content.

File: scripts/gen-function/parse.ts [hunk 2]
```diff
@@ -49,11 +52,11 @@ export function parse(content: string): Definition[] {
...
 function parseBlock(fn: string, body: string): Definition {
   // Remove '\n' in {variant} to make {variant} single line (ex. `searchpairpos`)
-  body = body.replaceAll(new RegExp(`^\(${fn}\\([^\)]*?\)\n\t*`, "g"), "$1");
+  body = body.replaceAll(new RegExp(`^(${fn}\\([^)]*?)\\n\\t*`, "gm"), "$1");
   // Append ')' for an invalid {variant}. (ex. `win_id2tabwin` in Neovim)
-  body = body.replaceAll(new RegExp(`^\(${fn}\\([^\)]*?\)\t+`, "g"), "$1)\t");
+  body = body.replaceAll(new RegExp(`^(${fn}\\([^)]*?)\\t+`, "gm"), "$1)\t");
   // Insert '\n' between {variant} and {document} (ex. `argidx`)
-  body = body.replaceAll(new RegExp(`^\(${fn}\\(.*?\\)\)\t`, "g"), "$1\n\t\t");
+  body = body.replaceAll(new RegExp(`^(${fn}\\(.*?\\))\\t`, "gm"), "$1\n\t\t");
```
Comment (Milly) [inline scripts/gen-function/parse.ts:59]: It is important to use multiline mode with `m`.
Regular expression escaping was fixed.

**Review by Shougo — APPROVED** [review]

**Review by lambdalisue — APPROVED** [review]
